# Generated by Django 2.0.6 on 2018-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
